sonar.organization=jemi3i
sonar.projectKey=jemi3i_angular-docker-app
sonar.projectName=angular-docker-app
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.typescript.lcov.reportPaths=coverage/lcov.info